import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

const appName = 'LOGO';
const appAndroidVersion = '1.0.0';
const appIosVersion = '1.0.0';
// String appLogoUrl = 'https://svgshare.com/i/170G.svg';
String appUrl = 'https://ba.biglike.app/';
final kDarkBlueColorOpacity = const Color(0xff000000).withOpacity(.07);
const String kFontFamilyNameHE = 'Noto Kufi Arabic';
const String kFontFamilyNameAR = 'Noto Kufi Arabic';
const String kFontFamilyName = 'Noto Kufi Arabic';
var kPrimaryColor = const Color(0xff00ADD6);
var kLightPrimaryColor = const Color(0xffF2FAFC);
var kNoteColor = const Color(0xff000000);
var kOrangeColor = const Color(0xffCC8421);
var kDarkCyanColor = kPrimaryColor;
var kLightCyanColor = const Color(0xfff0f1fd);
const kLightGrayColor = Color(0xffF0F0F0);
const kGrayColor = Color(0xffA1A1A1);
const kDarkGrayColor = Color(0xff727272);
const kMidGrayColor = Color(0xffDEDEDE);
const kBlackColor = Color(0xff0c0c0c);
const kLightBlackColor = Color(0xff1d1d1f);
const kRedColor = Color(0xff961A1A);
const kLightRedColor = Color(0xffFCE4E4);
const kBlueColor = Color(0xff160DF7);
const kWhiteColor = Color(0xffffffff);
const kLightWhiteColor = Color(0xfff9f9f9);
final kBorderRadius = BorderRadius.circular(13.r);
final kBorderRadius5 = BorderRadius.circular(5.r);
final kBorderRadius3 = BorderRadius.circular(3.r);
final kBorderRadius10 = BorderRadius.circular(10.r);
final kBorderRadiusOnly = Radius.circular(50.r);

// const kDarkCyanColor = Color(0xff37A596);
// final kLightCyanColor = const Color(0xff5CC8BB).withOpacity(.15);
// const kYellowColor = Color(0xffEBC420);
// const kBackGroundWhiteColor = Color(0xffF5F5F5);
// const kMidGrayColor = Color(0xffE2E2E2);
// const kDarkGrayColor = Color(0xffFEFEFE);
// const kBlueNavigateColor = Color(0xff1BB7E2);
// const kGreenWhatsappColor = Color(0xff2CB742);
// const kCallCustomerColor = Color(0xff883CD5);
// const kLightGreenColor = Color(0xffCDFBCD);
